name: CI/CD for Task Master

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-to-development:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to development server
        run: echo "✅ Deployed to development server"

  deploy-to-production:
    if: github.ref == 'refs/heads/production'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to production server
        run: echo "🚀 Deployed to production server"
